// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://failamyvdduolfpueahx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaWxhbXl2ZGR1b2xmcHVlYWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMDMwODQsImV4cCI6MjA3ODU3OTA4NH0.UIOsvXme0PvjpiquykotsPMp3h-ISzAcDBkayobL7Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});